---
title: "Identifying HAL"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

Please  enjoy these unique abalone ID cards created by [Oriana Poindexter](http://www.orianapoindexter.com). Each card has a front and back, and can be downloaded to your device as a PDF. 

<center>
<a class="btn btn-primary fa fa-question-circle" 
href="glossary.html" target="_blank" > Glossary of key terms</a>

```{r cards}
# htmltools::includeHTML("_cards.html")
librarian::shelf(
  htmltools, knitr, purrr, readr)

HTML('
<div class="container-fluid">
  <div class="px-lg-5">
    <div class="row">')

read_csv("cards.csv") %>% 
  pmap(
    function(...){
      with(list(...),
        knit_expand("_card.html"))
        }) %>% 
  unlist() %>% 
  HTML()

HTML('
    </div>
    <div class="py-5 text-right"><a href="http://www.orianapoindexter.com/id-guides" target="_blank" class="btn btn-dark px-5 py-3 rounded-pill">Source: Oriana Poindexter</a></div>
  </div>
</div>')
```