---
title: "Locating Hal"
output: html_document
---


```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(fontawesome)
```

`r fa(name = "hand-point-down")` Click on the dropdown below to see a map of known white abalone sightings, and the distribution of abalone species in the North Pacific

## {.tabset .tabset-dropdown}

### Known sightings of white abalone
![Known sightings of white abalone in California and Baja California. Circles indicate specimen records, squares indicate literature record, questions marks show a dubious record. Dots in red are new records not published in Geiger (2000), dots in green are from the Australian Museum, Sydney. Source: Daniel Geiger](./images/sore-map.gif)

### Distribution of Abalone in the North Pacific
![Distribution of the eight abalone species endemic to the North Pacific. Note that pinto and threaded are now considered the same species but with a northern and southern shell form that integrates in the area of Central California between the ranges shown in this map. (Map from NASA, ranges added by Genny Anderson indicating each species' general concentration, not full range). Source: Julie Bursek/CINMS?](./images/Ab_dist.jpg)
